apiVersion: apps/v1
kind: Deployment
metadata:
  name: unified-rag-service
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: unified-rag
  template:
    metadata:
      labels:
        app: unified-rag
    spec:
      containers:
      - name: rag-api
        image: ${YOUR_REGISTRY_PATH}/unified-rag:latest
        ports:
        - containerPort: 8080
        env:
        - name: NEO4J_URI
          value: "bolt://neo4j-retrieval-agent-eastus:7687"
        - name: NEO4J_USER
          value: "neo4j"
        - name: NEO4J_PASSWORD
          valueFrom:
            secretKeyRef:
              name: neo4j-credentials
              key: password
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
        readinessProbe:
          httpGet:
            path: /docs
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /docs
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: unified-rag-service
  namespace: default
spec:
  selector:
    app: unified-rag
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: neo4j-credentials
  namespace: default
type: Opaque
stringData:
  password: dedee-knowledge-graph!