apiVersion: apps/v1
kind: Deployment
metadata:
  name: retrieval-agent-eastus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retrieval-agent
  template:
    metadata:
      labels:
        app: retrieval-agent
    spec:
      containers:
      - name: chromadb
        image: dedeeregistry.azurecr.io/chromadb:v2.4
        ports:
        - containerPort: 8000
      - name: retrieval-table
        image: dedeeregistry.azurecr.io/retrieval-table:v4.1
        ports:
        - containerPort: 5001
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-secret
              key: OPENAI_API_KEY
        - name: RETRIEVAL_ID
          value: "eastus"
---
apiVersion: v1
kind: Service
metadata:
  name: retrieval-agent-eastus
spec:
  selector:
    app: retrieval-agent
  ports:
    - name: chromadb
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: retrieval-table
      protocol: TCP
      port: 5001
      targetPort: 5001
  type: LoadBalancer