version: '3.9'

services:
  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chroma-data:/chroma/chroma/
    environment:
      - IS_PERSISTENT=TRUE

  app:
    build: ./retrieval-table
    depends_on:
      - chromadb
    environment:
      - CHROMA_SERVER_HOST=chromadb
      - CHROMA_SERVER_PORT=8000
    ports:
      - "5001:5001"

volumes:
  chroma-data: