version: '3.9'

services:
  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chroma-data:/chroma/chroma/
    environment:
      - IS_PERSISTENT=TRUE

  app:
    build: ./retrieval-table
    depends_on:
      - chromadb
    environment:
      - CHROMA_SERVER_HOST=chromadb
      - CHROMA_SERVER_PORT=8000
      # Neo4j connection settings
      - NEO4J_URI=neo4j://128.203.120.208:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=dedee-knowledge-graph!
      # OpenAI API settings (replace with your actual key)
      - OPENAI_API_KEY=sk-proj-IYXxFiUbWs0CYZ31caQlT3BlbkFJQp03evB1IVRb1zbDHKo
      - OPENAI_MODEL=gpt-3.5-turbo
      # RAG settings
      - TOP_K_RESULTS=3
      - CANDIDATE_LIMIT=10
      - SIMILARITY_THRESHOLD=0.5
      - QUERY_WEIGHT=0.7
      - ANSWER_WEIGHT=0.3
      # ChromaDB settings
      - CHROMADB_COLLECTION=retrieval-table
      - CHROMADB_MAX_ITEMS=1000
      - CHROMADB_PERSIST_DIR=/app/chroma_cache
      - CHROMADB_SIMILARITY_THRESHOLD=0.85
    ports:
      - "5001:5001"
    volumes:
      - ./chroma_cache:/app/chroma_cache

volumes:
  chroma-data: