apiVersion: v1
kind: Service
metadata:
  name: judge-ollama-service
spec:
  selector:
    app: judge-ollama
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9200         # External port (used by orchestrator to call /judge/)
      targetPort: 11434  # Ollama’s internal port
