apiVersion: apps/v1
kind: Deployment
metadata:
  name: judge-ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: judge-ollama
  template:
    metadata:
      labels:
        app: judge-ollama
    spec:
      containers:
      - name: ollama
        image: ollama/ollama:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            set -e
            echo "Starting Ollama server...";
            ollama serve
        ports:
        - containerPort: 11434
        resources:
          limits:
            cpu: "750m"
            memory: "1.5Gi"
          requests:
            cpu: "300m"
            memory: "1Gi"
        env:
        - name: REDIS_HOST
          value: "shared-parent-memory.redis.cache.windows.net"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: password
        volumeMounts:
        - mountPath: "/ollama"
          name: ollama-storage

      - name: judge
        image: aashidutt3/debate-parent:latest
        imagePullPolicy: Always
        command: ["python", "-u", "judge.py"]
        workingDir: /app
        ports:
          - containerPort: 5001
        env:
        - name: REDIS_HOST
          value: "shared-parent-memory.redis.cache.windows.net"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: password
        - name: PARENT_ID
          value: "Judge-EastUS"
        - name: OLLAMA_MODEL
          value: "tinyllama"
        resources:
          limits:
            cpu: "500m"
            memory: "1Gi"
          requests:
            cpu: "250m"
            memory: "512Mi"
        volumeMounts:
        - mountPath: /app
          name: debate-code

      volumes:
      - name: ollama-storage
        emptyDir: {}
      - name: debate-code
        configMap:
          name: debate-script