apiVersion: apps/v1
kind: Deployment
metadata:
  name: judge-ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: judge-ollama
  template:
    metadata:
      labels:
        app: judge-ollama
    spec:
      nodeSelector:
        workload: gpu
      tolerations:
      - key: "sku"
        operator: "Equal"
        value: "gpu"
        effect: "NoSchedule"
      containers:
      - name: ollama
        image: ollama/ollama:latest
        command: ["ollama", "serve"]
        ports:
        - containerPort: 11434
        env:
        - name: OLLAMA_MODELS
          value: "mistral:7b"
        resources:
          requests:
            cpu: "3"
            memory: "16Gi"
            nvidia.com/gpu: 1
          limits:
            cpu: "4"
            memory: "16Gi"
            nvidia.com/gpu: 1
      - name: judge
        image: dedeeregistry.azurecr.io/judge:v2.5
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        env:
        - name: OLLAMA_MODEL
          value: "mistral:7b"
        resources:
          requests:
            cpu: "50m"       
            memory: "256Mi"
          limits:
            cpu: "250m"      
            memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: judge-ollama
spec:
  selector:
    app: judge-ollama
  ports:
    - name: ollama
      port: 11434
      targetPort: 11434
    - name: judge
      port: 5001
      targetPort: 5001
  type: LoadBalancer
