apiVersion: apps/v1
kind: Deployment
metadata:
  name: parent-ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parent-ollama
  template:
    metadata:
      labels:
        app: parent-ollama
    spec:
      nodeSelector:
        workload: gpu
      tolerations:
      - key: "sku"
        operator: "Equal"
        value: "gpu"
        effect: "NoSchedule"
      containers:
      - name: ollama
        image: ollama/ollama:latest
        command: ["ollama", "serve"]
        ports:
        - containerPort: 11434
        env:
        - name: OLLAMA_MODELS
          value: "gemma:3b"
        resources:
          requests:
            cpu: "3"
            memory: "8Gi"
            nvidia.com/gpu: 1
          limits:
            cpu: "4"
            memory: "12Gi"
            nvidia.com/gpu: 1
      - name: parent
        image: dedeeregistry.azurecr.io/parent:v2.6
        ports:
        - containerPort: 5001
        env:
        - name: PARENT_ID
          value: "eastus"
        - name: OLLAMA_MODEL
          value: "gemma:3b"
        resources:
          requests:
            cpu: "50m"       
            memory: "256Mi"
          limits:
            cpu: "250m"      
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: parent-ollama
spec:
  selector:
    app: parent-ollama
  ports:
    - name: ollama
      port: 11434
      targetPort: 11434
    - name: parent
      port: 5001
      targetPort: 5001
  type: LoadBalancer
