apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-device-westus-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-device-westus-2
  template:
    metadata:
      labels:
        app: edge-device-westus-2
    spec:
      containers:
      - name: chromadb
        image: dedeeregistry.azurecr.io/chromadb:v2.4
        ports:
        - containerPort: 8000
      - name: knowledge-base
        image: dedeeregistry.azurecr.io/knowledge-base:v1.1
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: edge-device-westus-2-service
spec:
  selector:
    app: edge-device-westus-2
  ports:
    - name: chromadb
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: knowledge-base
      protocol: TCP
      port: 5001
      targetPort: 5001
  type: LoadBalancer
